global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: identity-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'identity-service:8082' ]
        labels:
          ecosystem: healthcore

  - job_name: tracking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'tracking-service:8080' ]
        labels:
          ecosystem: healthcore

  - job_name: agenda-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'agenda-service:8080' ]
        labels:
          ecosystem: healthcore

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'notification-service:8086' ]
        labels:
          ecosystem: healthcore
