package com.healthcore.tracking.infrastructure.persistence.adapter;

import com.healthcore.tracking.domain.model.FoodLog;
import com.healthcore.tracking.domain.port.FoodLogPort;
import com.healthcore.tracking.infrastructure.persistence.entity.FoodLogDocument;
import com.healthcore.tracking.infrastructure.persistence.repository.SpringDataMongoFoodLogRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Driven Adapter (Infrastructure): Isolates the core domain from MongoDB specifics.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class FoodLogPersistenceAdapter implements FoodLogPort {

    private final SpringDataMongoFoodLogRepository repository;

    @Override
    public FoodLog save(FoodLog foodLog) {
        log.debug("Saving FoodLog to MongoDB for user.");
        FoodLogDocument document = toDocument(foodLog);
        FoodLogDocument savedDocument = repository.save(document);
        return toDomain(savedDocument);
    }

    @Override
    public List<FoodLog> findByUserIdAndDateRange(String userId, LocalDateTime start, LocalDateTime end) {
        log.debug("Querying MongoDB for FoodLogs by user and date range.");
        return repository.findByUserIdAndConsumedAtBetween(userId, start, end).stream()
                .map(this::toDomain)
                .collect(Collectors.toList());
    }

    private FoodLogDocument toDocument(FoodLog domain) {
        return FoodLogDocument.builder()
                .id(domain.getId())
                .userId(domain.getUserId())
                .barcode(domain.getBarcode())
                .foodName(domain.getFoodName())
                .consumedGrams(domain.getConsumedGrams())
                .totalCalories(domain.getTotalCalories())
                .totalProteins(domain.getTotalProteins())
                .totalCarbs(domain.getTotalCarbs())
                .totalFats(domain.getTotalFats())
                .consumedAt(domain.getConsumedAt())
                .build();
    }

    private FoodLog toDomain(FoodLogDocument document) {
        // Using the toBuilder() to assign the ID generated by MongoDB
        // while bypassing the strict domain validations on retrieval.
        return FoodLog.builder()
                .id(document.getId())
                .userId(document.getUserId())
                .barcode(document.getBarcode())
                .foodName(document.getFoodName())
                .consumedGrams(document.getConsumedGrams())
                .totalCalories(document.getTotalCalories())
                .totalProteins(document.getTotalProteins())
                .totalCarbs(document.getTotalCarbs())
                .totalFats(document.getTotalFats())
                .consumedAt(document.getConsumedAt())
                .build();
    }
}