services:
  # 1. El Motor de Base de Datos
  mongodb:
    image: mongo:7.0 
    container_name: healthcore-mongodb
    ports:
      - "27018:27017" 
    volumes:
      - mongo_data:/data/db 
    restart: unless-stopped 

  # 2. La Interfaz Gráfica
  mongo-express:
    image: mongo-express:latest
    container_name: healthcore-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false 
    depends_on:
      - mongodb 

  # 3. Nuestro API Gateway (NGINX)
  api-gateway:
    image: nginx:alpine # Usamos la versión ligera de NGINX
    container_name: healthcore-api-gateway
    ports:
      - "80:80" # El puerto por defecto de internet
    volumes:
      # Conectamos tu archivo de configuración hacia adentro del contenedor
      - ./services/api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - identity-service
      - tracking-service
    restart: unless-stopped

  catalog-service:
    build: ./services/catalog-service
    container_name: healthcore-catalog-service
    ports:
      - "50051:50051"
    restart: unless-stopped

  identity-service:
    build: ./services/identity-service
    container_name: healthcore-identity-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      # Apuntamos a la base de datos interna de Docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/healthcore_identity

  tracking-service:
    build: ./services/tracking-service
    container_name: healthcore-tracking-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - catalog-service
    environment:
      # Apuntamos a la BD y al contenedor de Python
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/healthcore_tracking
      # Si tu código Java usa localhost para gRPC, tendrás que cambiarlo a esta variable de entorno en el futuro
      - GRPC_CATALOG_TARGET=catalog-service:50051

volumes:
  mongo_data: