sonar.projectKey=HealthCore
sonar.projectName=HealthCore
sonar.projectVersion=1.0

# Exclude generated code and dependencies
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.venv/**,**/__pycache__/**,**/*.test.*,**/*.spec.*

sonar.modules=health-core,health-core-desktop,agenda-service,api-gateway,catalog-service,clinical-service,identity-service,media-service,notification-service,tracking-service

# Frontend
health-core.sonar.projectName=Frontend HealthCore
health-core.sonar.projectBaseDir=apps/health-core
health-core.sonar.sources=src

health-core-desktop.sonar.projectName=Desktop HealthCore
health-core-desktop.sonar.projectBaseDir=apps/health-core-desktop
health-core-desktop.sonar.sources=src

# Microservices (Java)
agenda-service.sonar.projectName=Agenda Service
agenda-service.sonar.projectBaseDir=services/agenda-service
agenda-service.sonar.sources=src/main
agenda-service.sonar.java.binaries=target/classes

clinical-service.sonar.projectName=Clinical Service
clinical-service.sonar.projectBaseDir=services/clinical-service
clinical-service.sonar.sources=src/main
clinical-service.sonar.java.binaries=target/classes

identity-service.sonar.projectName=Identity Service
identity-service.sonar.projectBaseDir=services/identity-service
identity-service.sonar.sources=src/main
identity-service.sonar.java.binaries=target/classes

notification-service.sonar.projectName=Notification Service
notification-service.sonar.projectBaseDir=services/notification-service
notification-service.sonar.sources=src/main
notification-service.sonar.java.binaries=target/classes

catalog-service.sonar.projectName=Catalog Service
catalog-service.sonar.projectBaseDir=services/catalog-service
catalog-service.sonar.sources=src

media-service.sonar.projectName=Media Service
media-service.sonar.projectBaseDir=services/media-service
media-service.sonar.sources=.

# Microservices (Nginx/API Gateway)
api-gateway.sonar.projectName=API Gateway
api-gateway.sonar.projectBaseDir=services/api_gateway
api-gateway.sonar.sources=.

# Microservices (Tracking)
tracking-service.sonar.projectName=Tracking Service
tracking-service.sonar.projectBaseDir=services/tracking-service
tracking-service.sonar.sources=src/main
tracking-service.sonar.java.binaries=target/classes
