spring:
  application:
    name: media-service

server:
  port: 8088

cloudflare:
  r2:
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    access-key-id: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
    secret-access-key: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
    region: auto

jwt:
  secret: ${JWT_SECRET}

grpc:
  server:
    port: 9091