spring:
  application:
    name: media-service

server:
  port: 8088

cloudflare:
  r2:
    endpoint: ${CLOUDFLARE_R2_ENDPOINT:https://tu-account-id.r2.cloudflarestorage.com}
    access-key-id: ${CLOUDFLARE_R2_ACCESS_KEY_ID:tu-access-key}
    secret-access-key: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY:tu-secret-key}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME:healthcore-media-dev}
    region: auto