spring.application.name=tracking-service

jwt.secret=${JWT_SECRET}
jwt.access-token-validity-ms=${JWT_ACCESS_TOKEN_VALIDITY_MS:300000}
jwt.refresh-token-validity-ms=${JWT_REFRESH_TOKEN_VALIDITY_MS:86400000}

spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASS}@localhost:27017/healthcore_tracking?authSource=admin

logging.level.com.healthcore.tracking=DEBUG

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.cache.type=redis
spring.cache.redis.time-to-live=86400000 # 24 hours in milliseconds
spring.cache.redis.cache-null-values=false