package com.healthcore.clinical.infrastructure.rest.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

@Schema(name = "LinkPatientRequest", description = "Payload used by a patient to connect to a nutritionist through a linking code.")
public class LinkPatientRequest {

    @Schema(description = "Temporary linking code generated by a nutritionist", example = "AB12CD")
    @NotBlank(message = "Linking code is required.")
    private String code;

    public LinkPatientRequest() {
    }

    public LinkPatientRequest(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}
