server:
  port: ${SERVER_PORT:8083} 

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

spring:
  application:
    name: clinical-service
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/healthcore_clinical}
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}

app:
  openapi:
    title: ${APP_OPENAPI_TITLE:HealthCore Clinical Service API}
    version: ${APP_OPENAPI_VERSION:1.0.0}
    description: ${APP_OPENAPI_DESCRIPTION:Clinical records, professional linking, observations and nutrition plans}
    server-url: ${APP_OPENAPI_SERVER_URL:http://localhost:8083}

grpc:
  agenda:
    target: ${GRPC_CLIENT_AGENDA_TARGET:agenda-service:50052}
  clinical:
    port: ${GRPC_CLINICAL_PORT:50051}
  catalog:
    target: ${GRPC_CATALOG_TARGET:catalog-service:50051}
  media:
    target: ${GRPC_MEDIA_TARGET:media-service:9091}
  client:
    identity-service:
      address: ${GRPC_CLIENT_IDENTITY_ADDRESS:static://localhost:50051}
      negotiation-type: plaintext

security:
  jwt:
    secret: ${JWT_SECRET:}
