server:
  port: ${SERVER_PORT:8083} 

spring:
  application:
    name: clinical-service
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/healthcore_clinical}
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}

grpc:
  agenda:
    target: ${GRPC_CLIENT_AGENDA_TARGET:agenda-service:50052}
  clinical:
    port: ${GRPC_CLINICAL_PORT:50051}
  catalog:
    target: ${GRPC_CATALOG_TARGET:catalog-service:50051}
  media:
    target: ${GRPC_MEDIA_TARGET:media-service:9091}
  client:
    identity-service:
      address: ${GRPC_CLIENT_IDENTITY_ADDRESS:static://localhost:50051}
      negotiation-type: plaintext

security:
  jwt:
    secret: ${JWT_SECRET:}
