# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"\x1e\n\x0b\x46oodRequest\x12\x0f\n\x07\x62\x61rcode\x18\x01 \x01(\t\"\xc4\x01\n\x0c\x46oodResponse\x12\x0f\n\x07\x62\x61rcode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\x12\x19\n\x11\x63\x61lories_per_100g\x18\x05 \x01(\x02\x12\x19\n\x11proteins_per_100g\x18\x06 \x01(\x02\x12\x16\n\x0e\x63\x61rbs_per_100g\x18\x07 \x01(\x02\x12\x15\n\rfats_per_100g\x18\x08 \x01(\x02\x12\x0e\n\x06source\x18\t \x01(\t\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"6\n\x0eSearchResponse\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.catalog.FoodResponse2\x93\x01\n\x12NutritionalCatalog\x12<\n\x0bGetFoodItem\x12\x14.catalog.FoodRequest\x1a\x15.catalog.FoodResponse\"\x00\x12?\n\nSearchFood\x12\x16.catalog.SearchRequest\x1a\x17.catalog.SearchResponse\"\x00\x42-\n\x1b\x63om.healthcore.catalog.grpcB\x0c\x43\x61talogProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.healthcore.catalog.grpcB\014CatalogProtoP\001'
  _globals['_FOODREQUEST']._serialized_start=26
  _globals['_FOODREQUEST']._serialized_end=56
  _globals['_FOODRESPONSE']._serialized_start=59
  _globals['_FOODRESPONSE']._serialized_end=255
  _globals['_SEARCHREQUEST']._serialized_start=257
  _globals['_SEARCHREQUEST']._serialized_end=302
  _globals['_SEARCHRESPONSE']._serialized_start=304
  _globals['_SEARCHRESPONSE']._serialized_end=358
  _globals['_NUTRITIONALCATALOG']._serialized_start=361
  _globals['_NUTRITIONALCATALOG']._serialized_end=508
# @@protoc_insertion_point(module_scope)
