name: HealthCore CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ==========================================
      # 1. ENTORNO JAVA (Identity & Tracking)
      # ==========================================
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests (Identity Service)
        working-directory: ./services/identity-service
        run: mvn clean test

      - name: Run Tests & Coverage (Tracking Service)
        working-directory: ./services/tracking-service
        run: mvn clean test

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Acelera el pipeline guardando las librerías en caché

      - name: Install dependencies (Catalog Service)
        working-directory: ./services/catalog-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Si tienes dependencias de test separadas, instálalas aquí también
          # pip install pytest pytest-cov grpcio-testing

      - name: Run Tests & Coverage (Catalog Service)
        working-directory: ./services/catalog-service
        run: pytest --cov=. --cov-report=term-missing